### ISSUE TITLE
New battery health has some issue

### ISSUE THREAD

**Issue by djpalmis** [jheredianet/Teslamate-CustomGrafanaDashboards#29]
I tried to set some custom value with no benefit.
I have a model 3 LR 2020 (so battery capacity shall be 75kWh or a little bit more).
![Screenshot_20230328_213237_Samsung Internet](https://user-images.githubusercontent.com/402122/228347797-fef629a5-9398-4dc5-a5a6-f3f1b4bd28a4.jpg)

**Comment by jheredianet** [comment]
Hi, give me some context about your data logged.
was this dashboard working in a previous version? Is this a clean Teslamate installation?
This dashboard works getting estimations from the charges session, and you must have at least one session charge that added  more than (let's say) 15kWh. 
As I can see in the graph you shared, only the ranges have been calculated, read from drivings/positions table and the current SOC, but it couldn't get any data from charges, that's why battery capacity cannot be calculated. 
Could you share a screenshot of your charges dashboard?

**Comment by jheredianet** [comment]
Hi @djpalmis 
I see. Everything seems to be fine. There's no problem about driving, since all estimations are based on chargers. It's really strange. 
Could you try this? Go to the "dashboard settings", then variables, then click on "aux" variable and scroll down. You should see preview of values like the following picture. Let me know if you got something or absolutely nothing. 

![image](https://user-images.githubusercontent.com/45735191/228657293-25fe005c-0bff-4cc6-b85f-1c61f2a34157.png)

**Comment by djpalmis** [comment]
![Screenshot_20230329_223330_Samsung Internet](https://user-images.githubusercontent.com/402122/228660740-93a99cc4-0a8b-4077-a0d1-a0509b4b4a90.jpg)
Something

**Comment by jheredianet** [comment]
Great, that's something. We have to dig a little bit more to see which query is not working. 
Could you run this query from your Database to see what you get? 

`
WITH PositionsCharges AS
(
	SELECT  date
        ,battery_level
        ,usable_battery_level
        ,rated_battery_range_km
        ,ideal_battery_range_km
	FROM positions
	WHERE car_id = 1
	AND ideal_battery_range_km is not null 
	UNION ALL
	SELECT  date
        ,battery_level
        ,coalesce(usable_battery_level,battery_level) AS usable_battery_level
        ,rated_battery_range_km
        ,ideal_battery_range_km
	FROM charges c
	JOIN charging_processes p
	ON p.id = c.charging_process_id
	WHERE p.car_id = 1
), AllRanges AS
(
	SELECT floor(extract(epoch from date)/86400)*86400 AS time
	       ,convert_km((SUM(rated_battery_range_km) / nullif(SUM(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric,'km') AS "rated_range_km"
	FROM PositionsCharges
	GROUP BY  1
), MaxRange AS
(
SELECT MAX("rated_range_km") AS "max_rated_range_km"
	FROM AllRanges
), CurrentRange AS
(
    SELECT convert_km(rated_battery_range_km,'km') /  nullif(coalesce(usable_battery_level,battery_level),0) * 100 AS "current_rated_range_km",
    usable_battery_level, convert_km(rated_battery_range_km,'km') AS "rated_battery_range_km"
    FROM positions WHERE  car_id = 1 AND (rated_battery_range_km IS NOT NULL AND usable_battery_level IS NOT NULL AND battery_level IS NOT NULL)
    ORDER BY "date" DESC LIMIT 1
), Aux AS
(
    SELECT charge_energy_added / NULLIF(convert_km(end_rated_range_km - start_rated_range_km,'km'), 0) * 100.0 AS DiscardValue FROM charging_processes
    WHERE car_id = 1 AND end_date IS NOT NULL AND end_rated_range_km IS NOT NULL AND start_rated_range_km IS NOT NULL
    ORDER BY end_date DESC LIMIT 1
), ChargesRAW AS
(
	SELECT  cp.id
        ,cp.end_date
        ,cp.charge_energy_added
        ,c.usable_battery_level
	FROM charging_processes cp
	INNER JOIN charges c
	ON cp.id = c.charging_process_id
	WHERE cp.car_id = 1 AND cp.charge_energy_added > (SELECT  DiscardValue FROM Aux)
), Charges AS
(
	SELECT  (100.0 * charge_energy_added) / (GREATEST(1,MAX(usable_battery_level) - MIN(usable_battery_level))) AS bc
	FROM ChargesRAW
	GROUP BY  id, charge_energy_added, end_date
	ORDER BY end_date DESC
), MaxCapacity AS
(
    SELECT MAX(bc) AS MaxCapacity FROM Charges
), 
CurrentCapacity AS
(
    SELECT CurrentRange."rated_battery_range_km" * Aux.DiscardValue /  CurrentRange.usable_battery_level  AS CurrentCapacity
    FROM CurrentRange, Aux
), Battery AS
(
	SELECT  (100.0 - (CurrentCapacity.CurrentCapacity * 100.0 / MaxCapacity.MaxCapacity)) AS Degradation FROM CurrentCapacity , MaxCapacity
) 
SELECT *
FROM MaxRange, CurrentRange, Aux, Battery, MaxCapacity, CurrentCapacity;
`

**Comment by djpalmis** [comment]
Ehm.. sorry to ask you this: How can I run a query?
In the meantime I'll go on searching on Google 😄

**Comment by jheredianet** [comment]
You should use any GUI postgresql client like pgAdmin or DBeaver, even Visual Studio Code has some free plug-ins for it.

**Comment by jheredianet** [comment]
As we discovered it has something to do with the database. It seems that there is some charging sessions not closed. It needs some data tweeks.
