### ISSUE TITLE
Current Drive View dashboard : Power unit does not seem right

### ISSUE THREAD

**Issue by MaxyMoos** [jheredianet/Teslamate-CustomGrafanaDashboards#3]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/949028cf24fd78d3e058665494570393ede8f721/dashboards/CurrentDriveView.json#L298

I haven't been able to confirm or to find any clear documentation regarding this, but I think that the `power` column in the `positions` table is given out in kilowatts (at least this looks like the right value when converting `max(power)` from kW to hp for my car).

The SQL query should be changed to use a multiplication constant of 1000, or change the panel unit to kilowatts.
Cheers for the very nice dashboards !

**Comment by jheredianet** [comment]
Hi @MaxyMoos, you are right. Good catch! Thanks for suggestion. I've changed the power unit to kW, then took the opportunity to add  a rated efficiency dotted line and change battery capacity calculation. 
May I kindly ask you to check it out and test "Current Drive View v1.1" dashboard?
Looking forward to know how it goes now in order to close the issue.
<img width="1888" alt="cdv" src="https://user-images.githubusercontent.com/45735191/211062783-ff4c772e-ad5d-453e-a7dc-f86a1131a2ab.png">

**Comment by MaxyMoos** [comment]
Hey that's great, thanks for the update, that looks much better 👍 
I got rid of the -30 / +30 kW fixed axis range in order to get an adaptative y-range for my drives though !

**Comment by jheredianet** [comment]
Hi @MaxyMoos I'm glad to hear that. About the -30/+30 (min/max value), I did it on purpose in order to have the elevation axis stacked on 0 to have a better view. I didn't find other way to do it. I got rid of it as well and realized that with the min value of the elevation axis on 0 was enough.
