### ISSUE TITLE
bug battery health on last update

### ISSUE THREAD

**Issue by SiNaPsEr0x** [jheredianet/Teslamate-CustomGrafanaDashboards#35]
Until the last update there were 47-48 kwh now 37-38... there is some error.. can you take a look?

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/5438823/231838511-a1906bb6-a262-4394-bc3d-6f46bbef4235.png">

**Comment by jheredianet** [comment]
Hi, 
yeah, it seems that you have a lot of degradation. I've tested the new estimations with different cars and no problem. 
About the ranges, it seen that you have lost 8.4km, it doesn't seem to be accurate, it's calculated on drives. 
Estimations for battery are totally based in charges and car efficiency in order to test you will need to get the queries from the dashboard and test it out to see if there is some missing or incoherent data. 

For example, the following is the stats of a Model 3 SR+ from 2020 and it seems to be coherent (Battery Capacity and Ranges)
![image](https://user-images.githubusercontent.com/45735191/231841702-399b51ec-8ef0-4bf2-a3cc-f59afde4d37d.png)

Any how if you want, contact me by twitter to privately test with you.

**Comment by SiNaPsEr0x** [comment]
this before last update

![IMG_5180](https://user-images.githubusercontent.com/5438823/231845267-67e9c479-08ed-46fc-97c6-d9558fd22bc9.jpeg)

**Comment by SiNaPsEr0x** [comment]
Exactly before I updated it said this:Inviato da iPhoneIl giorno 13 apr 2023, alle ore 19:48, Juan Carlos Heredia ***@***.***> ha scritto:﻿
Hi,
yeah, it seems that you have a lot of degradation. I've tested the new estimations with different cars and no problem.
About the ranges, it seen that you have lost 8.4km, it doesn't seem to be accurate, it's calculated on drives.
Estimations for battery are totally based in charges and car efficiency in order to test you will need to get the queries from the dashboard and test it out to see if there is some missing or incoherent data.
For example, the following is the stats of a Model 3 SR+ from 2020 and it seems to be coherent (Battery Capacity and Ranges)

Any how if you want, contact me by twitter to privately test with you.

**Comment by jheredianet** [comment]
Share a screenshot of chargers and efficiency dashboards from Teslamate. Just to see if there is something strange.

**Comment by SiNaPsEr0x** [comment]
![image](https://user-images.githubusercontent.com/5438823/231853435-123bd707-5ed6-41b6-9754-16d5acbb95d2.png)

![image](https://user-images.githubusercontent.com/5438823/231853468-096b36e7-b47a-4f66-86c5-5e5690772fda.png)

**Comment by SiNaPsEr0x** [comment]
If you look at the graph of the first screenshot of the battery (the line of red dots) you will notice that in the last one it lost 10kwh the scale

**Comment by jheredianet** [comment]
> ![image](https://user-images.githubusercontent.com/5438823/231853435-123bd707-5ed6-41b6-9754-16d5acbb95d2.png)
> 

From the efficiency graph, what I wanted to check, is this

![image](https://user-images.githubusercontent.com/45735191/231883591-27641cf1-6614-4051-a1a5-fdd526590fba.png)

What do you get there?

**Comment by SiNaPsEr0x** [comment]
![image](https://user-images.githubusercontent.com/5438823/231883910-567b86d1-3e8b-4956-b6d4-61769482951c.png)

**Comment by jheredianet** [comment]
I see. Everything seems to be fine. I don't know how to help. 
As I said before, estimations for battery are totally based in charges and car efficiency.
The difference from the previous version is that before I was using the "battery_level" field and now I'm using "usable_battery_level" which seems to be more accurate. Then I did a fine tuning on getting the max range and capacity. Also, in this case you could put your custom values to compare. 

In order to test you will need to get the queries from the dashboard and test it out to see if there is some missing or incoherent data. You should run the queries separately to find what's wrong. 

Sorry I cannot help, obviously, because I don't have your data, but you could try yourself and help me find what is wrong. 
What I can tell you is that this dashboard is being used by many users and it's having good feedback. 
Let me know if you find something or you can keep using the previous version if you feel confortable.

**Comment by SiNaPsEr0x** [comment]
It could be that usable is always lower when it’s cold as in these cases ... I’ll be able to tell you with a few more tests

**Comment by jheredianet** [comment]
It is, but that is why in the query you will see that it's only considering charges that added more kWh than your efficiency. 
In your case means that for estimations, it's only considering charging sessions with more or equal than 13,6kWh. 

Ok. Let me know if you do further investigations.

**Comment by jheredianet** [comment]
Hi @SiNaPsEr0x 
I have new. I've been researching and realized that I was not considering an estimation of the las charges but just the last one. As you suggested before sometime if battery is cold, there are some missed values. So, I've considered a month average. 

Could you check the developer branch? I've made the changes there. So, you can test. If it's ok, let me know and I will generate a new release.

**Comment by SiNaPsEr0x** [comment]
Luckily you’re a genius and you understand on the fly 😍 perfect I’ll take a look

**Comment by SiNaPsEr0x** [comment]
NOW its ok!!!


![image](https://user-images.githubusercontent.com/5438823/232346997-99382324-4d99-4425-ace7-c4979e1b02b1.png)

![image](https://user-images.githubusercontent.com/5438823/232347004-59b103f6-1c0d-4dc3-8695-0441d8f3c427.png)

**Comment by SiNaPsEr0x** [comment]
I revert to main and attend officially push

Thanks for fix

**Comment by jheredianet** [comment]
Thanks for your feedback. 
You have release v2.9.1 here https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2.9.1

Regards!
