### ISSUE TITLE
Current Charge View interface picture does not display

### ISSUE THREAD

**Issue by super-administrator** [jheredianet/Teslamate-CustomGrafanaDashboards#39]
The current charge view interface calls the URL of the gif picture https://i.imgur.com/bVfT1QW.gif, but sometimes the URL cannot be accessed and the picture cannot be displayed.
![屏幕截图 2023-08-02 043219](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/37964204/e9ef2b54-c931-4311-ac01-4978597b6b0a)

**Comment by jheredianet** [comment]
Hi, I see. Maybe it has to be something with your Internet provider. Do you recommend another public web site where to upload freely a gif image to change that URL?

**Comment by jheredianet** [comment]
Hi, I see. Maybe it has to be something with your Internet provider. I've changed the URL to point to Github since it supports GIFs as well. Check new release https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/new?tag=3.0.7

<img width="1905" alt="image" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/882f0b2f-7b0c-404d-954f-e9ddbb377ca5">
